services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    networks:
      - keycloak

  keycloak:
    container_name: keycloak_app
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - "9000:9000"
      - "8088:8088"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "password"
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: "INFO"
      KC_HTTP_PORT: "8088"
      KC_HTTP_HOST: 0.0.0.0
    depends_on:
      - db
    networks:
      - keycloak
    command:
      - 'start-dev'

networks:
  keycloak:
    name: keycloak
    driver: bridge

volumes:
  postgres: {}
